---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  namespace: foo
  labels: 
    foo: bar
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: pods-simple-container