extends: default

ignore: |
  /Tools/lula/
  Resources
  .terraform
  bats/bats-core/
  bats/test_helper/bats-assert/
  bats/test_helper/bats-support/

rules:
  comments:
    min-spaces-from-content: 1
  line-length:
    max: 250
    allow-non-breakable-inline-mappings: true
  truthy:
    check-keys: false
  document-start: disable
  indentation:
    spaces: 2
    check-multi-line-strings: false
  brackets:
    max-spaces-inside: 1
    max-spaces-inside-empty: 0
  braces:
    max-spaces-inside: 1
    max-spaces-inside-empty: 0
