apiVersion: s3.aws.crossplane.io/v1alpha3
kind: BucketPolicy
metadata:
  name: basic-bucketpolicy-deny-http
spec:
  forProvider:
    region: {{ .Values.region }}
    bucketNameRef:
      name: basic-bucket
    policy:
      version: '2012-10-17'
      statements:
        - sid: "denyHTTP"
          action:
            - S3:GetObject
          principal:
            awsPrincipals:
              - iamRoleArn: "*"
              - iamUserArn: "*"
          effect: Deny
          condition:
            - operatorKey: Bool
              conditions:
                - key: "aws:SecureTransport"
                  booleanValue: false
          resource:
            - "arn:aws:s3:::dci-basic-bucket/*"
