apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: block-public-access
  annotations:
    # This will be the actual bucket name. It must be globally unique, so you
    # probably want to change it before trying to apply this example.
    crossplane.io/external-name: block-public-bucket-{{ .Values.suffix }}
spec:
  forProvider:
    acl: private
    locationConstraint: {{ .Values.region }}
    objectOwnership: BucketOwnerPreferred
    publicAccessBlockConfiguration:
      blockPublicAcls: true
      blockPublicPolicy: true
      ignorePublicAcls: true
      restrictPublicBuckets: true
