apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: basic-rdsinstance
spec:
  forProvider:
    masterUsername: postgres
    allocatedStorage: 20
    dbInstanceClass: db.t2.small
    engine: postgres
    engineVersion: "12"
    region: {{ .Values.region }}
    skipFinalSnapshotBeforeDeletion: true
