apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: example-rdsinstance
spec:
  forProvider:
    allocatedStorage: 20
    dbInstanceClass: db.t2.small
    engine: postgres
    engineVersion: "12"
    masterUsername: masteruser
    publiclyAccessible: true
    region: {{ .Values.region }}
    skipFinalSnapshotBeforeDeletion: true
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: rds-pw-out-example
