apiVersion: sns.aws.crossplane.io/v1beta1
kind: Topic
metadata:
  name: authorised-bucket-topic-{{ .Values.suffix }}
spec:
  forProvider:
    displayName: authorised-bucket-topic-{{ .Values.suffix }}
    name: authorised-bucket-topic-{{ .Values.suffix }}
    region: {{ .Values.region }}
    policy: |
      {
        "Version": "2012-10-17",
        "Id": "example-ID",
        "Statement": [
            {
                "Sid": "Example SNS topic policy",
                "Effect": "Allow",
                "Principal": {
                    "Service": "s3.amazonaws.com"
                },
                "Action": [
                    "SNS:Publish"
                ],
                "Resource": "arn:aws:sns:{{ .Values.region }}:{{ .Values.accountID }}:authorised-bucket-topic-{{ .Values.suffix }}",
                "Condition": {
                    "ArnLike": {
                        "aws:SourceArn": "arn:aws:s3:*:*:authorised-bucket-{{ .Values.suffix }}"
                    },
                    "StringEquals": {
                        "aws:SourceAccount": "{{ .Values.accountID }}"
                    }
                }
            }
          ]
        }
