apiVersion: s3.aws.crossplane.io/v1alpha3
kind: BucketPolicy
metadata:
  name: bucketpolicy-deny-http
  annotations:
    # This will be the actual bucket name. It must be globally unique, so you
    # probably want to change it before trying to apply this example.
    crossplane.io/external-name: bucketpolicy-deny-http-{{ .Values.suffix }}
spec:
  forProvider:
    region: {{ .Values.region }}
    bucketNameRef:
      name: authorised-bucket
    policy:
      version: '2012-10-17'
      statements:
        - sid: "denyHTTP"
          action:
            - S3:GetObject
          principal:
            awsPrincipals:
              - iamRoleArn: "*"
              - iamUserArn: "*"
          effect: Deny
          condition:
            - operatorKey: Bool
              conditions:
                - key: "aws:SecureTransport"
                  booleanValue: false
          resource:
            - "arn:aws:s3:::authorised-bucket-{{ .Values.suffix }}/*"
