apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  creationTimestamp: null
  name: rds-multi-az-support
spec:
  rules:
    - exclude:
        resources: {}
      generate:
        clone: {}
      match:
        resources:
          kinds:
            - RDSInstance
      mutate: {}
      name: rds-multi-az-support
      validate:
        message: rds-multi-az-support must be enabled. Set spec.forProvider.multiAZ.
        pattern:
          spec:
            forProvider:
              multiAZ: true
  validationFailureAction: enforce
status:
  ready: false
